// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_content_delivery_bucket: 'oelement-login-hostingbucket-master',
  aws_content_delivery_bucket_region: 'us-east-2',
  aws_content_delivery_url:
    'http://oelement-login-hostingbucket-master.s3-website-us-east-1.amazonaws.com',
  aws_cognito_identity_pool_id:
    'us-east-2:67468b07-48a7-4667-9d28-4fd81103e63d',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_HbcTnaJeh',
  aws_user_pools_web_client_id: 'u91ju7pmh94or7thsmehfs9n5',
}

export default awsmobile
